language: python
python: 2.7

before_install:
 - travis_retry wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
 - chmod +x miniconda.sh
 - bash miniconda.sh -b -p $HOME/miniconda
 - export PATH=/home/travis/miniconda/bin:$PATH
 - conda update --yes conda

install:
  - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
  - source activate test
  - conda install --yes numpy scipy pip scikit-learn pandas
  - pip install setuptools
#  - [ ... some other packages to install ... ]
  - python setup.py install

script:
  - python -m unittest discover
